### ISSUE TITLE
Tls 1.2

### ISSUE THREAD

**Issue by jeroenpasman** [delegateas/Daxif#20]
When trying to deploy webresources to a 9.0 environment I kept getting an error "Unable to connect to CRM". 
I managed to fix it by adding this to the script:

````
open System.Net

ServicePointManager.SecurityProtocol <- SecurityProtocolType.Tls12
````

Since 9.0 it's mandatory to use TLS 1.2 and its backward compatible. Hence why I added it. 
I recon you guys have a better place to add this line.

**Comment by TomMalow** [comment]
We have had similar problem with our other tools and have solved it by upgrading them to use .NET Framework 4.6.2 which uses TLS 1.2 by default. For some reason, Daxif have not been upgraded and still uses 4.5.2 which default to TLS 1.0. We do not experience the same problem when using Daxif on 9.0 environments but we believe it is caused by using a newer version of F# in our projects.

We will see if it possible to upgrade to 4.6.2. In the the meantime, continue to use the added line in your script.

**Comment by TomMalow** [comment]
We have released a version 4.2.1 which should fix this issue. Can you update Daxif and test if it works without setting the Security Protocol to TLS 1.2 ?

**Comment by jeroenpasman** [comment]
Thanks for the reply, unfortunately this didn't help. 
At first I thought it was the CRM SDK version, as the error I got was:

`Metadata contains a reference that cannot be resolved: https://org.crm4.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=8.2`

Changed the dll to version 9.0, but without success. Setting the TLS solved it again.

**Comment by jeroenpasman** [comment]
Tried installing 4.1 and works like a charm. Guess I'll take that route. 
Thanks for the effort!
