### ISSUE TITLE
Custom API support (execution stage = internal/30)

### ISSUE THREAD

**Issue by markschouten** [delegateas/Daxif#54]
Plugins configured to be executed from/in a Custom API are registered in the 'internal' execution stage by selecting the Plugin Type in Power Platform.

![image](https://user-images.githubusercontent.com/34807044/141287109-5742f75a-9098-4090-86d5-b385f78a83a8.png)

![image](https://user-images.githubusercontent.com/34807044/141286731-c632d749-7e22-49a6-bc3b-cf6dff85e1f5.png)

Solution/request:
Add 'Internal' to ExecutionStage, so plugins can be specified to run in the Internal execution stage.
Plugins specified to run in the Internal execution stage do not need to be registered (I don't think this is even possible), but they are executed when the corresponding Custom API triggered.

![image](https://user-images.githubusercontent.com/34807044/141287592-4dd22b56-7c7e-48d5-a10e-b91bbbf4954f.png)

Things I've done:
I already added Internal to the ExecutionStage enum, but then registration fails.
When registered manually using the Plugin Registration tool, the plugin gets triggered when calling the Custom API.

![image](https://user-images.githubusercontent.com/34807044/141288506-c1853a04-33fe-4844-b0ea-687df170b9dd.png)

**Comment by misoeli** [comment]
I guess your title tells the story - custom API's are not supported currently.
I have added it to the backlog, but I can't give any indications as to when it would be implemented.

**Comment by mkholt** [comment]
The issue seems to be two-parts, given that the docs are correct and the api configuration is part of the solution package:
1. We need to be able to sync the plugin class either without a registration (this seems risky, could potentially include wrong classes), or using a meta-registration for custom APIs.
2. The Plugin.cs base class needs to be able to find/execute the proper method on custom-api calls, so we hook into the existing logic to get service access.

Additionally, XrmMockup should probably be extended to support executing Custom API steps on-demand.

**Comment by misoeli** [comment]
We have started work on this, and the latest preview release (5.3.0-alpha) contains a draft version. Source can be found here: [https://github.com/delegateas/Daxif/tree/custom-api-mlr](https://github.com/delegateas/Daxif/tree/custom-api-mlr) - there's still a few gotcha's to be aware of - see [https://github.com/delegateas/Daxif/wiki/Custom-API-Setup](https://github.com/delegateas/Daxif/wiki/Custom-API-Setup)

**Comment by bo-stig-christensen** [comment]
@markschouten : This has been implemented and is included in latest version 5.5.1 that we have just released.

In order to activate and make use of Custom APIs you must use the **CustomAPI.cs** base class from Daxif resources for creating Custom APIs. - It works similarly to plugins inheriting from **Plugin.cs** and you register it according to the documentation linked by @misoeli above.
