### ISSUE TITLE
When adding multiple custom APIs with same request/response parameter names it only registers the request/response parameters for one custom API

### ISSUE THREAD

**Issue by robertraaijmakers** [delegateas/Daxif#72]
**Describe the bug**
When you have multiple Custom APIs and use the same request & response parameter names. It will only register the request & response parameters of one Custom API instead of all.

**To Reproduce**
See screenshots :)

**Expected behavior**
That all custom APIs have request & response parameters.

**Screenshots**
![image](https://github.com/delegateas/Daxif/assets/1773099/aa8c039c-edf3-4e1f-b41d-5eb5496589be)
![image](https://github.com/delegateas/Daxif/assets/1773099/ff567b43-03b7-47ba-9baa-373632c661d8)

Very simplified example of the situation. In this case, only on our first (Async) the request parameters are added. on the other one, no request parameters are added.

**Environment**
- CRM/D365/CDS version: 9.x
- Tool version: 5.5.1

**Additional context**
I think the error is in the compare: https://github.com/delegateas/Daxif/blob/29d0d76bbac53c69de96645b582e965fb0b4b080/src/Delegate.Daxif/Modules/Plugins/Compare.fs#L66
There is also a "TODO" compare more :) I think the "More" should be that it also compares on the "Custom API" the request/response parameter is linked to.

**Comment by robertraaijmakers** [comment]
I've tested the pull request, the code builds and still works on my project, however, it still only sync one of the request and response parameter. So I'm missing something but I don't have any idea how I can debug the code while running so I can try to figure out what I'm missing.

**Comment by robertraaijmakers** [comment]
Figured it out together with a colleague, it is now working! :) (see pull request)

**Comment by skovlund** [comment]
This should be fixed already.

The fix was merged in #62 (specifically in this [commit](https://github.com/delegateas/Daxif/commit/303c180bc370997373d8809ccb9a6fe39a56c0ba)). 

We thought it was released as part of Delegate.Daxif version 5.0.0, but on closer inspection all relevant changes were made to CustomAPI.cs which isn't released as part of that package. Instead it is released as part of Delegate.Daxif.Scripts, but no new version of this has been released since the update was made.

For now I recommend that you manually download or copy the contents of [CustomApi.cs](https://github.com/delegateas/Daxif/blob/master/src/Delegate.Daxif.Scripts/Resources/CustomAPI.cs) to ensure you have the newest most updated version of the file.

**Comment by robertraaijmakers** [comment]
Thanks @skovlund , there are indeed some changes between the new and our CustomApi.cs file and will check in 2 weeks if this works on our project as well :)

**Comment by robertraaijmakers** [comment]
This works with the correct files and can be closed. Thanks!
